### ISSUE TITLE
Test and fix search 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#129]
- there are duplicate results TBC

ran "land" and couldn't get duplicates
![image](https://user-images.githubusercontent.com/18452161/185005342-86766df7-842f-4811-8d3c-0a12b1dc5257.png)
 to test 'decline' - couldn't get any results

**Comment by AnaBelgun** [comment]
@mpaget Hi, would you please re-test this and let us know if still not working, We have updated the index and included an automated way to run it.

**Comment by mcass-abares** [comment]
Duplicate results still occur when using the Location search bar or searching the data catalogue using the location search bar. (24 November 2022). I'm not sure what the difference is with the location search returns. Data layer duplicates are because search returns are being drawn from both Australia and Global tab. 
![DuplicateDatalayersearchreturns_20221124](https://user-images.githubusercontent.com/9258954/203648253-b74a0792-0789-474c-a933-4a65e56023d4.png)
![DuplicateLocations_Parkes20221124](https://user-images.githubusercontent.com/9258954/203648262-23b7a310-618a-4e24-b0c7-7960143743ac.png)

**Comment by AnaBelgun** [comment]
hi @nf-s I don't think there is an issue with search per se, right? Location results are drawn from a couple of geocoders and data search duplicates might be because of tabs.

**Comment by meh9** [comment]
The search is correct - as far as the system is concerned these are two different layers. It is purely coincidental that they have the same name:

<img width="657" alt="Screen Shot 2022-11-24 at 09 32 55" src="https://user-images.githubusercontent.com/5283003/203657128-6f5d1207-ab0a-4572-9110-dde63a48960b.png">

<img width="752" alt="Screen Shot 2022-11-24 at 09 33 23" src="https://user-images.githubusercontent.com/5283003/203657193-aa821a2a-124c-4a10-be13-199e2c9c62df.png">

**Comment by meh9** [comment]
There is an interesting bug here though, if you search the catalogue without having clicked on the different catalogue tabs you only get a partial path:

<img width="490" alt="Screen Shot 2022-11-24 at 09 39 06" src="https://user-images.githubusercontent.com/5283003/203657823-e7330de0-7ab9-43f5-a25f-16171bec1dac.png">

However, if you:
1. Open the catalogue
2. click on the Global tab
3. click back to the Australia tab
4. then search
The path shown on hover shows the full path:
<img width="636" alt="Screen Shot 2022-11-24 at 09 38 41" src="https://user-images.githubusercontent.com/5283003/203657934-f6af2bd3-a5de-42ae-854a-31ffe3ee9748.png">

We should fix that so the full path is always displayed.

**Comment by nf-s** [comment]
Different "Parkes" results are coming from the geocoder API.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/6187649/203662439-e2c30128-50a8-4e56-ab95-7ddb809353aa.png">

@meh9 is correct in that both those layers are separate, so they will both appear in search results.

**Comment by mcass-abares** [comment]
Thanks for looking into this. I can't see the hover over at all. This path location would be extremely helpful. Is there anything I should have done to enable this?

**Comment by mcass-abares** [comment]
Ok I see the hover over is available for data catalogue entries not locations. It would be great to have something like this for locations to be able to make an informed choice about which Geocoder return to choose e.g. the information you show above about the confidence of the return except I still can't see what the difference is between return 2-5.

 Agree with your point above about not getting full paths when searching the whole catalogue without selecting "global" or "Australia" that would also be useful.
